### ISSUE TITLE
JUnit test report is not rendered nicely

### ISSUE THREAD

**Issue by abendt** [thilo11/lambdacd-junit#1]
Hi,

we configured lambdacd-junit to display our JUnit test reports. However it is not rendered nicely (Screenshot). Do we have to configure something?
![bildschirmfoto 2017-07-12 um 15 42 54](https://user-images.githubusercontent.com/370821/28120688-06fa6f44-6719-11e7-93a2-0ae8cf074c03.png)

**Comment by thilo11** [comment]
Is this still an issue? If not please drop a line.
